#    _____                  _             ________
#   / ___/__  ________   __(_)   ______ _/ / ____/___  ________
#   \__ \/ / / / ___/ | / / / | / / __ `/ / /   / __ \/ ___/ _ \
#  ___/ / /_/ / /   | |/ / /| |/ / /_/ / / /___/ /_/ / /  /  __/
# /____/\__,_/_/    |___/_/ |___/\__,_/_/\____/\____/_/   \___/
#

Functions:
  Spawn:
    Setted: false
    world:
    x:
    y:
    z:
    yaw:
    pitch: