name: SurvivalCore
authors: [FrancyPro]
version: '${version}'
main: gq.francypro149.survivalcore.SurvivalCore
softdepend: [ Vault ]
api-version: 1.20
commands:
  survival:
    aliases: []
  economy:
    aliases: ["eco", "econ"]
